databases:
  - name: hackdb
    plan: free
    databaseName: hack
    user: hack

services:
  - type: web
    plan: free
    name: hack
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn hack.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hackdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4