databases:
  - name: hackdb
    plan: free
    databaseName: hack
    user: hack

services:
  - type: web
    name: soacha-web
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn hack.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hackdb
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: soacha-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /healthz

  - type: worker
    name: soacha-worker
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "celery -A hack worker -l info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hackdb
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: soacha-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  - type: redis
    name: soacha-redis
    plan: free
    ipAllowList: []
